### ISSUE TITLE
Geosite 规则 `category-ai-chat-!cn` 导致在ClashMetaForAndroid客户端导入时发生错误

### ISSUE THREAD

**Issue by koast18** [7Sageer/sublink-worker#114]
## 问题描述
选定默认的Balanced配置时，由这个[commit](https://github.com/7Sageer/sublink-worker/commit/34c483d3d6cd4ae2defc95adb5027d6b2cc1b694)引入的Geosite 规则 `category-ai-chat-!cn` 导致在ClashMetaForAndroid客户端导入时发生错误 即使是这个客户端最新版本 也是没办法成功导入的

## 环境信息
- [ClashMetaForAndroid](https://github.com/MetaCubeX/ClashMetaForAndroid) 
- 版本v2.11.7

## 原始节点信息：
无需这个部分。

## 操作步骤
无

## 预期行为
成功导入。

## 尝试过的解决方案
也许应该同时加入以下配置以保证`category-ai-chat-!cn`这类较新的geosite能够被正确的找到。

```
geodata-mode: true
geodata-loader: memconservative
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"
```

题外话：
其实`category-ai-chat-!cn`包含的AI相关域名并不全 比如aistudio.google.com里检查地区的api域名就没被代理 导致进入这个页面就会被强制跳转到不支持的地区的提示页面

- [x] 我确认没有找到解决相同问题的 issue
