### ISSUE TITLE
请教个 github action 部署的问题

### ISSUE THREAD

**Issue by fscarmen** [7Sageer/sublink-worker#12]
大佬，我有个项目在vps也是用 wrangler 部署的。我想改为通过 action 部署，参考本项目，我在 cf 上设置了 token ，但部署时说权限问题。我没有用到 r2，我的yml文件如下，求教，谢谢！
```
name: Deploy Worker
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '21'
      
      - name: Install dependencies
        run: npm install
      
      - name: Install wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3.7.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
```

报错
![image](https://github.com/user-attachments/assets/012bbcda-07a3-46c3-a423-32d1e5b7b3fb)

cf Token 的设置

<img width="1114" alt="image" src="https://github.com/user-attachments/assets/8f1e3fb9-c56b-4f7b-b26a-8ca1cc0fa100">

github 上设置的变量

<img width="1186" alt="image" src="https://github.com/user-attachments/assets/fa972346-e4e9-4ea3-bb32-48b0be3cb2a9">
