### ISSUE TITLE
Stash 中无法解析 geosite

### ISSUE THREAD

**Issue by up1and** [7Sageer/sublink-worker#144]
## 环境信息
- Stash 2.8.0

## 问题描述
生成的配置文件 Clash Verge 和 OpenClash 都可以正常运行。

出问题的配置在于这一段：

```
nameserver-policy:
    geosite:cn,private:
      - https://120.53.53.53/dns-query
      - https://223.5.5.5/dns-query
    geosite:geolocation-!cn:
      - https://dns.cloudflare.com/dns-query
      - https://dns.google/dns-query
```

Stash 应该是无法兼容 geosite:cn,private 这种写法的配置，会报错 unmarshal errors cannot unmarshal !!seq into string。

删去 nameserver-policy 后又会造成规则模式无法正确分流。

官网的配置样例只有这种写法

```
nameserver-policy:
    'www.baidu.com': 114.114.114.114
    '+.internal.crop.com': system
```

配置样例 https://stash.wiki/configuration/example-config.zh

感谢作者的付出，很棒的订阅转换工具。

## Update

重新参考了下案例，DNS 服务器的配置替换成官网的样例是可以正常工作的。

```
dns:
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
    - system # 使用 iOS 系统 DNS

  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    - system

  nameserver-policy:
    "www.baidu.com": 114.114.114.114
    "+.internal.crop.com": system
```
