### ISSUE TITLE
请求支持自定义dns

### ISSUE THREAD

**Issue by bingoku** [7Sageer/sublink-worker#47]
支持某些域名的使用自定义dns。

clash和singbox都有类似的设置。

应用场景很多，个人的测试域名，内部网络一些域名都需要这种设置。

```yaml
dns:
  use-system-hosts: true
  prefer-h3: true
  ipv6: true
  cache-algorithm: arc
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
    - '+.msftconnecttest.com'
    - '+.msftnsci.com'
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query#h3=true
  proxy-server-nameserver:
      - https://doh.pub/dns-query
  fallback:
    - https://1.1.1.1/dns-query#节点选择
    - https://dns.google/dns-query#节点选择
  fallback-filter:
      geoip: true
      geoip-code: CN
      ipcidr:
        - 240.0.0.0/4
      domain:
        - '+.google.com'
        - '+.facebook.com'
        - '+.youtube.com'
        - '+.instagram.com'
  nameserver-policy:
    '+.devdev1.cn': 'https://dns.yyds.cn/dns-query/mydns'
    '+.auok.cn': 'https://dns.yyds.cn/dns-query/mydns'
    '+.ok123.pub': 'https://dns.yyds.cn/dns-query/mydns'
    '+.devops.com': 'https://dns.yyds.cn/dns-query/mydns'
    "geosite:cn,private,apple,microsoft,onedrive":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
```
